### ISSUE TITLE
Add integrated service tests

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/ruby-bgs#19]
It'd be nice to be able to run the specs to test the return values of all the services. Right now, I'm having to go into the console and do someting like this, and inspect the output manually.

```
require_relative "./spec/spec_helper.rb"
c = get_client
require "pp"
pp c.veteran.find_by_file_number("633792224")
```

**Comment by alisan16** [comment]
This hasn't been updated in over 3 years. Closing.
