### ISSUE TITLE
Throw informative exception exception on SOAP fault

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/ruby-bgs#20]
From the efolder outage (department-of-veterans-affairs/appeals-deployment#270), we notice that the SOAPFault from ruby_bgs is not being logged in cloudwatch. Because of this, we wasted a lot of engineering time chasing the wrong issues.

At a glance, ruby-bgs is re-throwing this error (https://github.com/department-of-veterans-affairs/ruby-bgs/blob/master/lib/bgs/base.rb#L110).

Right now, any time BGS returns an error, it throws a very misleading exception:

```
NoMethodError (undefined method `key?' for nil:NilClass):
 app/services/bgs_service.rb:21:in `fetch_veteran_info'
 app/models/download.rb:33:in `block in <class:Download>'
 app/models/search.rb:66:in `validate!'
 app/models/search.rb:23:in `perform!'
 app/controllers/downloads_controller.rb:13:in `create'
```

**Comment by alisan16** [comment]
This hasn't been updated in over 3 years. Closing.
