### ISSUE TITLE
Remove Gemfile.lock 

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/ruby-bgs#40]
Ruby-bgs shouldn't have a Gemfile.lock since it's a gem. This should be fixed, as it constrains dependencies for any application that relies on ruby-bgs See http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/

## AC
- Gemfile.lock is no longer checked in
- All necessary dependencies are present in the gemspec and are pinned to appropriate major/minor versions
- Ruby-bgs is tested in Caseflow and successfully makes calls to bgs

**Comment by kierachell** [comment]
**PASSED**

yeah, it's gone
