### ISSUE TITLE
claims.find_by_vbms_file_number returns empty array if there is just one claim

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/ruby-bgs#56]
If a veteran has just a single end product, the structure of the XML returned by the BGS `find_benefit_claim` service is a little different. We do not parse it correctly:

Many claims:
```
...
<return>
  ...
  <participantRecord>
    <numberOfRecords>2</numberOfRecords>
    <returnCode>SHAR 9999</returnCode>
    <returnMessage>Records found</returnMessage>
    <selection>
      <benefitClaimID>65909351</benefitClaimID>
      ...
    </selection>
    <selection>
      <benefitClaimID>62209351</benefitClaimID>
      ...
    </selection>
  </participantRecord>
  ...
</return>
```

1 claim:
```
...
<return>
  ...
  <participantRecord>
    <benefitClaimID>62209351</benefitClaimID>
    ...
  </participantRecord>
  ...
</return>
```

This is causing a sync error: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/1936/

## Acceptance criteria
- When a veteran has just one EP, the response from `BenefitClaimServiceBean.findBenefitClaim` should be parsed as an array with one item, not an empty array.

**Comment by kahlouie** [comment]
The sync error is now happening here:https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2138/

**Comment by leikkisa** [comment]
@kahlouie  I think we can consider this validated because I just did an intake for VBMS testing that had one EP on it (we looked at it earlier tonight together), Veteran: 123458310

Will let you make the final call in case there is anything else you want to do for validation.

**Comment by kahlouie** [comment]
Yep, moved to Done. Thanks for testing it.
