### ISSUE TITLE
Add DocumentService to ruby_bgs

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/ruby-bgs#65]
Add DocumentService to ruby_bgs with:

manageClaimantLetter_V2
generateTrackedItem

Potentially add findClaimantLetters so that we can verify our work.

Depending on what BGS says about when we will do this, potentially add:
manageThirdPartyLetter_V2
findThirdPartyLetters

**Comment by shanear** [comment]
This will be validated via https://github.com/department-of-veterans-affairs/caseflow/issues/7118, closing
