### ISSUE TITLE
Remove filters on claimants

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/ruby-bgs#78]
Do not filter out non-dependents.

See https://github.com/department-of-veterans-affairs/caseflow/issues/10251

**Comment by alisan16** [comment]
Is this causing errors? Should this be prioritized?

**Comment by pkarman** [comment]
https://github.com/department-of-veterans-affairs/caseflow/issues/11162 is the relevant ticket

**Comment by leikkisa** [comment]
Closing - the other folks being returned are fiduciaries, and we've gotten confirmation that they are not claimants.
